### ISSUE TITLE
`io.micronaut.core.annotation.Nullable` has stereotype `@Nonnull(when = When.MAYBE)` on it hence fails on null properties supplied

### ISSUE THREAD

**Issue by soberich** [micronaut-projects/micronaut-serialization#134] opened 2022-02-20 21:43 UTC
### Expected Behavior

`io.micronaut.core.annotation.Nullable` should make parameter non-required, nullable.

### Actual Behaviour

This on is kind of nonsense... so annotation `io.micronaut.core.annotation.Nullable` has `@Nonnull(when = When.MAYBE)`, so this module - Serde - makes annotated properties required, non-nullable 🥇 
:)
When I removed annotation `io.micronaut.core.annotation.Nullable` after several hours of trials and failures- it worked!

`io.micronaut.core.annotation.AnnotatedElement`
```java
    /**
     * @return Whether the element is declared as not being null
     */
    default boolean isNonNull() { // this gives `true` for property annotated with `io.micronaut.core.annotation.Nullable` 
        return getAnnotationMetadata().hasStereotype(AnnotationUtil.NON_NULL);
    }
```

### Steps To Reproduce

I guess it simple enough from description.

### Environment Information

Serge m7
micronaut 3.3.3

### Version

3.3.3

**Comment by yawkat** [comment] 2022-02-21 08:14
Hi soberich,

We encountered a similar issue when working on making micronaut-data work with serde. Also see: https://github.com/micronaut-projects/micronaut-core/issues/6795

The problem here is that `io.micronaut.core.annotation.Nullable` should never appear in the annotation metadata in the first place. In core, [there is a transformer](https://github.com/micronaut-projects/micronaut-core/blob/3.3.x/inject/src/main/java/io/micronaut/inject/annotation/internal/CoreNullableTransformer.java) that ensures this. However, as discussed in the issue, if you have a custom mapper that applies to `Nullable`, it is still possible to have the annotation wrongly present in the metadata. Please verify that you do not have such a mapper present (maybe from an old data version).

I will close this as it's a duplicate of the -core issue.

**Comment by soberich** [comment] 2022-02-22 19:15
@yawkat I don't have any custom annotation mappers.
What I do have is this line in `lombok.config`
```log
lombok.addNullAnnotations = CUSTOM:io.micronaut.core.annotation.NonNull:io.micronaut.core.annotation.Nullable
```
If this is the cause, than I'd say there should be big red header about it, because this kind of feature/bug cost quite some time to resolve. You would never think that `@Nullable` causes `@Nonnull` to be implied.
Isn't that too fragile to rely on the fact that something should never be somewhere? Could it be a good idea to throw an exception then with proper error message if it should **never** be present in metadata?

**Comment by soberich** [comment] 2022-02-22 19:15
@yawkat I don't have any custom annotation mappers.
What I do have is this line in `lombok.config`
```log
lombok.addNullAnnotations = CUSTOM:io.micronaut.core.annotation.NonNull:io.micronaut.core.annotation.Nullable
```
If this is the cause, than I'd say there should be big red header about it, because this kind of feature/bug cost quite some time to resolve. You would never think that `@Nullable` causes `@Nonnull` to be implied.
Isn't that too fragile to rely on the fact that something should never be somewhere?

**Comment by graemerocher** [comment] 2022-02-22 19:24
@soberich could you provide an example with how to reproduce?

**Comment by soberich** [comment] 2022-02-22 22:06
with `@Nullable`
<img width="1681" alt="image" src="https://user-images.githubusercontent.com/25544967/155227268-eb2ea076-7819-48d9-9b5c-77e316039659.png">
without `@Nullable`
<img width="1681" alt="image" src="https://user-images.githubusercontent.com/25544967/155227328-6cc4b799-4e43-4cc1-b807-a8e8c976f720.png">
So virtually with there is no way to indicate it is nullable, unless, of course, `Optional`
<img width="1681" alt="image" src="https://user-images.githubusercontent.com/25544967/155227448-f01eb27e-1bb6-45b9-9269-152aed2be661.png">
Hope this helps to repro. 
Thanks!

**Comment by graemerocher** [comment] 2022-02-24 15:40
You can fix this by upgrading to `micronaut-data` 3.3.0-M1 since the bug is there. When Micronaut 3.4 is final and this library is final it will be a non-issue

**Closed by graemerocher** 2022-02-24 15:40 UTC

**Comment by soberich** [comment] 2022-02-24 19:54
@graemerocher, sorry I could not make it practical. 
This issue is regaring `micronaut-serialization` and if I can extrapolate it to `..-core` what does it have to do with `*-data`?
In a repro there is a `data-processor` but I believe it not related to that.
So what is the workaround exactly?

**Comment by soberich** [comment] 2022-02-25 07:48
@graemerocher @yawkat I'd appriciate a workaround description. It's unclear. Thanks a lot in advance!

**Comment by graemerocher** [comment] 2022-02-25 08:20
The issue is this class in `micronaut-data-processor` in Micronaut Data 3.2.x https://github.com/micronaut-projects/micronaut-data/blob/3.2.x/data-processor/src/main/java/io/micronaut/data/processor/mappers/support/NullableAnnotationMapper.java

This class doesn't exist in 3.3.x, hence if you upgrade this dependency the problem goes away

**Comment by soberich** [comment] 2022-02-25 15:50
@graemerocher in my main app this **didn't change anything**, so pulling hairs again.
I managed to adjust reproducer so you can see it for yourself.
Works as you said 👍 
<img width="1631" alt="image" src="https://user-images.githubusercontent.com/25544967/155744137-28462703-e551-4d44-97d1-5f48d53c74de.png">
however some combinations dependencies which present in main code break this balance
<img width="1631" alt="image" src="https://user-images.githubusercontent.com/25544967/155744406-cdc6847b-c298-4346-aebe-9a3de074c4e5.png">

It was quite some trials before removing !! GUAVA worked. So of course the reason that over combo succeeds is that 
<img width="502" alt="image" src="https://user-images.githubusercontent.com/25544967/155744965-0de0fa75-5162-40d2-83b8-696d2ba28e5c.png">
<img width="1631" alt="image" src="https://user-images.githubusercontent.com/25544967/155745109-8746de74-d290-446e-afbd-c9ac4078491f.png">
I hope this helps to resolve!

**Comment by soberich** [comment] 2022-03-01 18:24
If it's still qualified as not a bug, please, maybe a comment. We are experiencing quite a lot of trouble with build / setup being quite fragile due to this kind of issue. It's just POC, so, it would be great to prove that concept is viable.

**Comment by graemerocher** [comment] 2022-03-01 18:55
Provide a PR or sample that reproduces

**Comment by soberich** [comment] 2022-03-02 09:33
@graemerocher there is a repro attached to this issue all along. It never stopped being a working repro. I am not sure, is it not visible for you, @graemerocher ?
