### ISSUE TITLE
Micronaut Serialization deserializes model bean with inheritance and discriminator property incorrectly, causing HTTP POST to REST endpoint to fail

### ISSUE THREAD

**Issue by runenielsen** [micronaut-projects/micronaut-serialization#581] opened 2023-09-26 11:15 UTC
### Expected Behavior

Micronaut Serialization should set the discriminator property in an OpenAPI model bean with inheritance when deserializing.

Note that the model in the example is generated by Micronaut OpenAPI and the annotation `@JsonIgnoreProperties` is used for the discriminator with `allowSetters` set to `true`. This works fine with Jackson.

### Actual Behaviour

Micronaut Serialization does not set the discriminator property in an OpenAPI model bean with inheritance when deserializing.

This causes validation of the bean to fail, since this property is required in the specification and therefore annotated with `@NotNull`.

This is a critical bug for us, since it prevents valid models generated with Micronaut's OpenAPI generator from being posted to REST endpoints, if jakarta validation is used.

I think it is related to https://github.com/micronaut-projects/micronaut-serialization/issues/550

### Steps To Reproduce

1. Clone the repository https://github.com/runenielsen/mn-discriminator-null-serde-bug, that uses Micronaut Serialization.
2. Run the testPostModelWithDiscriminator in BookInfoControllerTest to post the model with a discriminator to a service endpoint with validation.
3. See that the test fails due to a validation failure "bookInfo.type: must not be null".
4. Now clone the repository https://github.com/runenielsen/mn-discriminator-not-null-with-jackson, that contains the same code, but uses Jackson Databind instead of Micronaut Serialization.
5. See that the same test succeeds.

### Environment Information

- MacOS
- JDK 17

### Example Application

https://github.com/runenielsen/mn-discriminator-null-serde-bug

### Version

4.1.2

**Comment by graemerocher** [comment] 2023-09-27 09:38
probably a duplicate of #550 currently `allowSetters` is unsupported and should fail with a compilation error

**Comment by runenielsen** [comment] 2023-09-27 10:23
@graemerocher : Thanks for the reply.

1. That `allowSetters` is not supported for `@JsonIgnoreProperties` seems to be missing from the [documentation](https://micronaut-projects.github.io/micronaut-serialization/latest/guide/index.html#jacksonAnnotations). There's no notes about it in the table with Jackson annotations.
2. I think this is a fairly critical missing feature, since it makes Micronaut Serialization unusable with OpenAPI specs using inheritance. It will at least prevent us from using it. Is there any plan for when you will support `allowSetters`?
3. I would call this is an undocumented feature, whereas #550 definitely seems to be a bug (Micronaut Serialization should never add the same property twice when serializing to JSON, also I don't think I even use `allowSetters` in the example application in that issue). So I wouldn't say this is a duplicate.

**Comment by graemerocher** [comment] 2023-09-27 10:32
1. yes this is a bug it should fail compilation
2. Now that there is a ticket there is a plan to support it for sure
3. noted

**Comment by runenielsen** [comment] 2023-09-27 10:59
Thanks again 🙂

**Comment by runenielsen** [comment] 2023-11-03 07:54
@dstepanov :

Thanks for your effort, it is very much appreciated! And sorry if I came off a bit grumpy yesterday, it was a long day 😉 

Can we move the discussion from #550 to here? As I wrote, I think your observations on the `visible` property on `@JsonTypeInfo` are more related to this issue than #550 (see discussion in #550 on this).

I agree with your findings in relation to the `visible` property on `@JsonTypeInfo`. So in conclusion I think the fix for this issue (#581) is to add support to Micronaut Serialization for the `visible` property on `@JsonTypeInfo`.

I will report an issue in the Micronaut OpenAPI Generator project, that the `visible` property should also be added to the generated models for Micronaut Serialization. But this can not be fixed until after support has been added to Micronaut Serialization for the `visible` property, since Micronaut Serialization currently fails with this error, when the `visible` property is added:

```
/Users/rune.nielsen/projects/jsonignorepropertiesnotworking/src/main/java/example/micronaut/BookInfo.java:26: error: Annotation @JsonTypeInfo specifies attribute 'visible'. Currently supported attributes include: [include, use, property, defaultImpl]
public class BookInfo {
```

I assume this is why the `visible` property was removed from the models generated by the Micronaut OpenAPI Generator for Micronaut Serialization in the first place. It is just a shame that this makes Micronaut Serialization unusable for models with inheritance and validation generated by Micronaut OpenAPI Generator 🙂 

So in my view, adding support for the `visible` property should have high priority.

On a side-note, I totally agree, that it would be nice to get all the issues you list in [this comment in the other issue](https://github.com/micronaut-projects/micronaut-serialization/issues/550#issuecomment-1790820801) fixed.

**Comment by dstepanov** [comment] 2023-11-03 07:57
Support for `visible` already merged https://github.com/micronaut-projects/micronaut-serialization/pull/638

**Comment by runenielsen** [comment] 2023-11-03 09:22
@dstepanov : I have now created [this issue](https://github.com/micronaut-projects/micronaut-openapi/issues/1273) in the Micronaut OpenAPI Generator project and written in it, that the fix shouldn't be released before the fix you did here.

**Closed** 2023-11-03 16:35 UTC
Labels: type: enhancement
